# gemeinsame Hilfsfunktionen, unten aktuell Ideen
def show_main_menu() 
def filter_by_time(recipes, max_minutes): ...
def filter_by_complexity(recipes, level): ...
def filter_by_diet(recipes, diet_type): ...
def filter_by_course(recipes, course_type): ...
def get_random_recipe(recipes): ...
def create_new_recipe(): ...
def search_by_ingredient(recipes, ingredient): ...
def adjust_portions(recipe, target_servings): ...
